### ISSUE TITLE
Getting HitHub Actions Updated Automatically

### ISSUE THREAD

**Issue by Karim-53** [Karim-53/Compare-xAI#19]
The _awesome_ tool dependabot lets you scan your used GitHub Marketplace Actions and lets you know if they are in need of an update.

The update is proposed via a pull request, which can be accepted or declined, it will itself take care of deleting pull requests if these become irrelevant.

You specify the configuration in the file: `.github/dependabot.yml` in your repository using this action - actually it scans all your actions.

```yaml
# Basic dependabot.yml file
# REF: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
```

## Todo
- [ ] Create a PR containing one new file:   `.github/dependabot.yml`
- [ ] change the interval to a monthly update 
- [ ] make sure the action is working correctly on your fork
