### ISSUE TITLE
Fix the Spellcheck Action

### ISSUE THREAD

**Issue by Karim-53** [Karim-53/Compare-xAI#20]
# Todo
- [ ] Follow the instruction in `https://github.com/rojopolis/spellcheck-github-actions` to add a config file that include the options described below:
- [ ] fix the current error `Error: Files in repository contain spelling errors` by adding a config file that target *.py  *.md and optionally *.yml
- [ ] Language should include both en_US and German
- [ ] In `https://github.com/Karim-53/Compare-xAI/blob/main/.github/workflows/spellcheck.yml` change `rojopolis/spellcheck-github-actions@0.28.0` to the latest version
- [ ] Make sure the Action is working perfectly
